### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Vincentvanleeuwen** [theonejonahgold/frontend-applications#1]
✓ Gitignore 
✓ No junk files found!
- [x] Repo description update: Maybe add that it's also a D3 project
- [x] Missing concept, data used and image in readme!
- [x] Data not described. (empty values, invalid values etc.) in readme
✓ Link to site
- [x]  No features listed in readme
- [x] No aknowledgements in readme

**Wiki**
✓ Wiki is written well, I can read through it easily and understand the concepts.
- [x] There is a conceptual process page, however, it might be nice to add a code process page as well.

✓ Framework is described well
- [x]  "Dit is **vergeljkbaar** met Vue." (spelling error @https://github.com/theonejonahgold/frontend-applications/wiki/Svelte-basics)

✓ Strong arguments, very enthusiastic about Svelte.
✓ States and components well documented.

##Rubric Scores
**Application of subject matter 9-10**
You have a great understanding of JavaScript and Svelte and apply it in a professional way. You found a great way of rendering components with Svelte and D3.
**Understanding 9-10**
You always know how to solve everyone's problem, and you are great at holding a nerdy conversation :p
**Quality 7-8**
Code quality is perfect to me, your wiki just needs some maintenance.
**Process 5 - 6**
Need to show a little bit more progress!

**Comment by jonahgoldwastaken** [comment]
done!
